### ISSUE TITLE
Receipt Cards not getting rendered on the Facebook Messenger channel

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotFramework-Services#115]
Tested the 06.Using-Cards sample from the Botbuilder-Samples. The facebook messenger channel does not support rendering of the receipt cards.

Steps to Reproduce

- Run the 06.Using-Cards sample and test it on the messenger channel.

- When you click on the 'Receipt Cards' , it responds back with 'Sorry, it looks like something went [wrong'.[](url)](url
![RC](https://user-images.githubusercontent.com/48731427/63729387-e4cfb300-c81b-11e9-9a9b-f939ba08c803.png)
)

The Cx reported the same [issue](https://stackoverflow.com/questions/57601582/is-there-a-message-sorry-it-looks-like-something-went-wrong-on-channel-line) about the receipt card not getting rendered while testing their code on the messenger channel.
[bug]

**Comment by mickeydjw** [comment]
Does this need to remain open?  We have a bug open for the issue.

**Comment by v-kydela** [comment]
@bwamie - Is this fixed?

**Comment by CoHealer** [comment]
Confirmed the bug fix has been merged:
Merged PR 10411: Fix facebook channel receipt quantity bug.

**Comment by johseffer** [comment]
I'm using the version 10.0.4 of the SDK and the problem still here, the receipt cards are showed fine at the bot framework emulator but dont do when using the facebook messeger channel.
