### ISSUE TITLE
Receiving "Conversation ID not found" errors in adapter's onTurnError

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-Services#203]
## Versions
NodeJS v10.16.3
BotBuilder NodeJS SDK v4.6.2
OS: NodeJS Docker Image

## Describe the bug
In the production, our bot service adapter's onTurnError listener is receiving plenty of but intermittent errors for directline channel users. When printed the error object, it looks like below
```
{ Error: Conversation ID not found","stream":"stderr","time":"2020-04-11T09:39:47.034381068Z"}
```
Some of the conversation IDs for which the errors have occurred are below:
```
LkrMRVxnwvD4VIM2sbSO7t-h
Gz8jVK8ZDbj3NZGk7kXfjD-h
EBEQvQQyvmIKmfDiWlWBhq-h
5s9G9tEbk2Y2YCWUpAPLEn-h
```
We are not able to reproduce this error and identify the root cause of it. 
Please guide us in understanding in what scenarios this may happen or how to debug so we can fix them.

**Comment by craigjensen** [comment]
The fix has been deployed.  Please reopen if you see this again

**Comment by bhushanvadgave** [comment]
@craigjensen 
Errors are still occurring in our bots.
Below are some of the conversation Ids for which error occurred.
`
LrgaRN4IOeV9Thpi3vt8vA-h
SdwjhlmM1X4zgjJfzh6Ke-h
9V2gmnWSiTRKrcCQWcxfaG-h
BccRGINMspOJOkQ8jOiUHQ-h
`

**Comment by craigjensen** [comment]
There's a scenario that the original fix didn't address but it appears to be a fairly rare corner case.  We'll get a fix ready but knowing how often you are seeing this will help us prioritize getting it deployed.

**Comment by bhushanvadgave** [comment]
@craigjensen The error count varies from 5 to 20 per day depending on usage by the customers.

**Comment by craigjensen** [comment]
The fix will go out in the next deployment which is planned for this week

**Comment by craigjensen** [comment]
Fix has been deployed - please reopen if you see this again
