### ISSUE TITLE
[TRACKING] & in user names causes mentions to miss text property

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/BotFramework-Services#204]
## Versions
SDK 4.8
nodejs v10.20.1

## Describe the bug
Teams allows the & character in user names. When a user sends a message to a bot and mentions a user with the & character, the entities mention object is missing the 'text' property (`<at>username</at>`) causing functions like TurnContext.removeMentionText to fail.

## To Reproduce
Create a user in Teams called "Test ($~&)"
Send a message to your bot while @ mentioning the user above
The message received by the bot contains the mention in entities but the 'text' property is missing:

```
{ mentioned:
     { id:
        '29:16xB25CaNg2TuYGVNbiEyHpb5T5N9-5al1bghslxHEhlc8FE-2EizBGV9a-YI9Z8V4JtgLbQmFp1VCJG92UDFRw',
       name: 'Test ($~&)' },
    type: 'mention' }
```

## Expected behavior
text property should be `<at>Test ($~&)</at>`

```
{ mentioned:
     { id:
        '29:16xB25CaNg2TuYGVNbiEyHpb5T5N9-5al1bghslxHEhlc8FE-2EizBGV9a-YI9Z8V4JtgLbQmFp1VCJG92UDFRw',
       name: 'Test ($~&)' },
    type: 'mention',
    text: '<at>Test ($~&)</at>' }
```

**Comment by Gousia-MSFT** [comment]
@matthiasdilger Thanks for reporting this. I have raised a bug for this.

**Comment by jwiley84** [comment]
https://github.com/microsoft/botbuilder-js/issues/2111

**Comment by matthiasdilger** [comment]
Hi, the issue is still present (using SDK 4.9)

Bot receives message:
```
{
  text: '<at>XXX</at> <at>Test ($~&)</at> this is a test\n',
  textFormat: 'plain',
  attachments: [
    {
      contentType: 'text/html',
      content: '<div><div><span itemscope="" itemtype="http://schema.skype.com/Mention" itemid="0">XXX</span> <span itemscope="" itemtype="http://schema.skype.com/Mention" itemid="1">Test ($~&amp;)</span>&nbsp;this is a test</div>\n' +
        '</div>'
    }
  ],
  type: 'message',
  timestamp: 2020-06-06T00:28:30.465Z,
  localTimestamp: 2020-06-06T00:28:30.465Z,
  id: '1591403310445',
  channelId: 'msteams',
  serviceUrl: 'https://smba.trafficmanager.net/apac/',
  from: {
    id: '29:1DCZ0wphWBgNg0DE7_Re5iE5G8nd-aEpuR4lYhF08z9KNU2B3PQd6eDn-MNi5-PjjBlwTlNJlGXCgVW-PZGgoqg',
    name: 'XYZ',
    aadObjectId: '3a46e4de-c1ff-47b8-b750-17522bc7e33e'
  },
  conversation: {
    isGroup: true,
    conversationType: 'channel',
    tenantId: 'a80db8af-20a3-49c1-ba16-757fe42179ed',
    id: '19:b72ee83fe6be47578920b77d05874add@thread.skype;messageid=1591403310445'
  },
  recipient: {
    id: '28:b3442ca1-8d58-459f-a94c-88d4a4310c9e',
    name: 'XXX'
  },
  entities: [
    { mentioned: [Object], text: '<at>XXX</at>', type: 'mention' },
    { mentioned: [Object], type: 'mention' },
    {
      locale: 'en-US',
      country: 'US',
      platform: 'Mac',
      type: 'clientInfo'
    }
  ],
  channelData: {
    teamsChannelId: '19:b72ee83fe6be47578920b77d05874add@thread.skype',
    teamsTeamId: '19:b4d780bd0d584f44b360ddde97d6cdef@thread.skype',
    channel: { id: '19:b72ee83fe6be47578920b77d05874add@thread.skype' },
    team: { id: '19:b4d780bd0d584f44b360ddde97d6cdef@thread.skype' },
    tenant: { id: 'a80db8af-20a3-49c1-ba16-757fe42179ed' }
  },
  locale: 'en-US',
  rawTimestamp: '2020-06-06T00:28:30.4651115Z',
  rawLocalTimestamp: '2020-06-06T08:28:30.4651115+08:00',
  callerId: 'urn:botframework:azure'
}
```

And just the mention:

```
{
    mentioned: {
      id: '29:16xB25CaNg2TuYGVNbiEyHpb5T5N9-5al1bghslxHEhlc8FE-2EizBGV9a-YI9Z8V4JtgLbQmFp1VCJG92UDFRw',
      name: 'Test ($~&)'
    },
    type: 'mention'
  }
```

As you can see, the text property is still missing.

**Comment by Nikitha-MSFT** [comment]
The bug is not fixed. We are tracking it internally, We don't have ETA to share when it will be available.

**Comment by cleemullins** [comment]
Spoke with @tacri and She will sync with @Wajeed-msft to figure out how to drive this forward.

**Comment by Wajeed-msft** [comment]
Internal Tracker: [Bug 889851: & in user names causes mentions to miss text property](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/889851)

**Comment by tacri** [comment]
The root cause has been identified and we are investigate possible fixes for the issue.

**Comment by arturl** [comment]
I see from our internal records that the issue is resolved and we're waiting for the fix to be deployed worldwide. Will close the ticket when the deployment is confirmed.

**Comment by arturl** [comment]
The fix is in, if you still see this issue let us know.

**Comment by matthiasdilger** [comment]
Issue still there (using SDK 4.9)

```
{
    mentioned: {
      id: '29:16xB25CaNg2TuYGVNbiEyHpb5T5N9-5al1bghslxHEhlc8FE-2EizBGV9a-YI9Z8V4JtgLbQmFp1VCJG92UDFRw',
      name: 'Test ($~&)'
    },
    type: 'mention'
  }
```

This mention should also have

`text: '<at>Test ($~&)</at>'`

**Comment by arturl** [comment]
@tacri, can you please take a look at the new repro from @matthiasdilger above?
