### ISSUE TITLE
Failed to decrypt conversation id for format *==@p2p.thread.skype

### ISSUE THREAD

**Issue by huyjack178** [microsoft/BotFramework-Services#270]
Hi, currently, our old skype group has id with this format 19:I3RyYW5jaHVvbmc4Mi8kYW5ocGRfYnM7MzZjNzE3ZjFjMjI4YWI4MA==@p2p.thread.skype

And when send via bot framework, I got this Failed to decrypt conversation id error in portal
Can you help me solve this problem?
![image](https://user-images.githubusercontent.com/11793001/101130022-498bd700-3635-11eb-8444-fcf1cd983258.png)

**Comment by MichaelHaydenAtMicrosoft** [comment]
Transferring to Skype Team

**Comment by konstlut** [comment]
This is a confirmed bug on Skype backend side. The issue has been mitigated for the specific bot and the general fix will be rolled out on the first week of January.
@huyjack178 , @MichaelHaydenAtMicrosoft , @hcyang

**Comment by MichaelHaydenAtMicrosoft** [comment]
@konstlut Wanted to check to see if the fix was rolled out already and if we can close this issue since it has been mitigated.

**Comment by konstlut** [comment]
Yes, we believe the problem should be fixed for all bots and all conversations in Skype and Microsoft Teams. Thank you, @MichaelHaydenAtMicrosoft

**Comment by MichaelHaydenAtMicrosoft** [comment]
Thank you @konstlut! Closing issue.

**Comment by danghoanghai** [comment]
> Thank you @konstlut! Closing issue.

hi @MichaelHaydenAtMicrosoft . I see that the issues have not fixed. Why this issue closed? I still keep monitoring it. 
hi @konstlut Please notify me when the issues have been fixed. Thanks :)

**Comment by MichaelHaydenAtMicrosoft** [comment]
@danghoanghai , can we get a fresh new set of logs? We want to check to see if there is another issue. Root cause for original issue has been addressed per our developers.

**Comment by danghoanghai** [comment]
@MichaelHaydenAtMicrosoft ya, sure. Here are the errors I got a few minutes ago before I comment on this post.
If you need more information (group ID, bot ID), please contact me by my email. I will provide you, even add you and your bot into my error group. The error still Not Found
>
![image](https://user-images.githubusercontent.com/18319715/106106192-c049da00-6177-11eb-89d2-a6e1af67a7a6.png)

**Comment by MichaelHaydenAtMicrosoft** [comment]
@konstlut, please see above comment for new customer logs.

**Comment by MichaelHaydenAtMicrosoft** [comment]
@danghoanghai, @huyjack178 - looks like our engineers found a different issue and adjusted the configuration. Can you try again and see if an error is generated? If so, please give us any error codes or timestamps that may be associated. Thank you!

**Comment by danghoanghai** [comment]
hi @MichaelHaydenAtMicrosoft the error is the same as above. Conversation not found. 
![image](https://user-images.githubusercontent.com/18319715/106981914-87bc8880-6795-11eb-99f3-7a9327e562bc.png)
Here is the image with the timezone GMT +7 (Vietnam). Hope it will be helpful.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Thank you! @konstlut please see above

**Comment by azenchenko** [comment]
@danghoanghai there seems to be two different issues that happened to your bot and in original report here. We have un-flighted your bot from experimental feature that might cause Conversation Not Found error. Can you please check again and let me know if there'd be an issue again by providing timestamp and conversationid.
Thanks!

**Comment by MichaelHaydenAtMicrosoft** [comment]
@konstlut , please see comment above.

**Comment by MichaelHaydenAtMicrosoft** [comment]
@danghoanghai - See above. Please check to see if you are getting the same error. If so, please provide timestamp and Conv ID.

**Comment by hojojon** [comment]
@azenchenko @MichaelHaydenAtMicrosoft I still have the same problem as @danghoanghai does. The timestamp is "2021-02-24 10:04:55.043936+09:00" and my conversation id is "19:I2hlb3F1YXk3MC8kc2YuLi4xMjM7ZGRiZWFkZGEwYzdiOTgwZA==@p2p.thread.skype".

![image](https://user-images.githubusercontent.com/17516086/108934668-5a764280-7690-11eb-8906-3d2e93189153.png)

**Comment by kaisunc** [comment]
I'm getting

 {"error":{"message":"Conversation id does not support uppercase characters"}}

for any target chat ids similar to hojojon.

**Comment by danghoanghai** [comment]
> @danghoanghai - See above. Please check to see if you are getting the same error. If so, please provide timestamp and Conv ID.

hi Micheal, I still cannot send messages to my chat group. Here is the result from Azure: 
![image](https://user-images.githubusercontent.com/18319715/108964462-13974580-76ae-11eb-92bf-e40e9c3345d6.png)
and here is my conversation ID: **19:I3NlbGVuYTExNTg4LyQyMTgxYThkZDE4YWY3NDFj@p2p.thread.skype**

If you want to add your bot to this group for convenience to testing, please send me your contact or your bot contact privately. Thanks

**Comment by MichaelHaydenAtMicrosoft** [comment]
@danghoanghai @hojojon 
Thank you for your patience.  From what I understand, there is an issue with our internal partner service that was mitigated with a workaround that doesn't work for some scenarios. They have disabled the workaround and would like you to repro one more time so as to help in the original issue being debugged and ultimately fixed. Apologies for asking you to do this again.

@azenchenko @konstlut  can fill in the needed details here.

**Comment by danghoanghai** [comment]
> @danghoanghai @hojojon
> Thank you for your patience. From what I understand, there is an issue with our internal partner service that was mitigated with a workaround that doesn't work for some scenarios. They have disabled the workaround and would like you to repro one more time so as to help in the original issue being debugged and ultimately fixed. Apologies for asking you to do this again.
> 
> @azenchenko @konstlut can fill in the needed details here.

thank Michael, I have tested and the bot can send messages now. Thank you for your support and thank dev team for the effort.

**Comment by hojojon** [comment]
@MichaelHaydenAtMicrosoft Thank you for your support. I've checked again and now I don't see any error. My bot works correctly as before.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Great! Glad to hear that this now working! I am going to close this issue.
